export const myCategories = ['Table', 'Chair', 'Sofa', 'tile', 'wall'];
export const categories = [
  'Moderna Microwave',
  'Infinity Refrigerator',
  'Apex Dishwasher',
  'Lumina Range',
  'Evolution Oven',
  'Cosmos Cooktop',
  'Vantage Ventilation Hood',
  'Zenith Blender',
  'Innovate Coffee Maker',
  'Nova Toaster',
  'Pure Microwave',
  'Zen Refrigerator',
  'Sleek Dishwasher',
  'Clean Range',
  'Simple Oven',
  'Zenith Cooktop',
  'Shadow Ventilation Hood',
  'Minimalist Blender',
  'Streamlined Coffee Maker',
  'Essential Toaster',
  'Forge Microwave',
  'Raw Refrigerator',
  'Steel Dishwasher',
  'Forge Range',
  'Rustic Oven',
  'Forge Cooktop',
  'Metal Ventilation Hood',
  'Forge Blender',
  'Industrial Coffee Maker',
  'Iron Toaster',
  'Nexus Microwave',
  'Quantum Refrigerator',
  'Matrix Dishwasher',
  'Cosmos Range',
  'Solar Oven',
  'Horizon Cooktop',
  'Orb Ventilation Hood',
  'Digital Blender',
  'Futuristic Coffee Maker',
  'Future Toaster',
  'Vintage Microwave',
  'Classic Refrigerator',
  'Nostalgia Dishwasher',
  'Retro Range',
  'Antique Oven',
  'Classic Cooktop',
  'Timeless Ventilation Hood',
  'Retro Blender',
  'Vintage Coffee Maker',
  'Old-fashioned Toaster',
  'Glamour Microwave',
  'Gatsby Refrigerator',
  'Artisan Dishwasher',
  'Deco Range',
  'Chic Oven',
  'Art Deco Cooktop',
  'Elegance Ventilation Hood',
  'Luxury Blender',
  'Art Deco Coffee Maker',
  'Elite Toaster',
  'Pop Microwave',
  'Colorful Refrigerator',
  'Funky Dishwasher',
  'Vibrant Range',
  'Playful Oven',
  'Pop Cooktop',
  'Groovy Ventilation Hood',
  'Whimsical Blender',
  'Pop Art Coffee Maker',
  'Bold Toaster',
  'Eames Microwave',
  'Atomic Refrigerator',
  'Nelson Dishwasher',
  'MCM Range',
  'Retro Oven',
  'MCM Cooktop',
  'Sputnik Ventilation Hood',
  'Atomic Blender',
  'MCM Coffee Maker',
  'Danish Toaster',
  'Boho Microwave',
  'Natural Refrigerator',
  'Eclectic Dishwasher',
  'Boho Range',
  'Organic Oven',
  'Boho Cooktop',
  'Artisanal Ventilation Hood',
  'Bohemian Blender',
  'Rustic Coffee Maker',
  'Handmade Toaster',
  'Hygge Microwave',
  'Nordic Refrigerator',
  'Minimalist Dishwasher',
  'Scandinavian Range',
  'Simple Oven',
  'Nordic Cooktop',
  'Light Ventilation Hood',
  'Minimal Blender',
  'Scandinavian Coffee Maker',
  'White Toaster',
  'Zenith Microwave',
  'Infinity Refrigerator',
  'Elite Dishwasher',
  'Fusion Range',
  'Contemporary Oven',
  'Modern Cooktop',
  'Sleek Ventilation Hood',
  'Contemporary Blender',
  'High-Tech Coffee Maker',
  'Contemporary Toaster',
  'High-Tech Coffee Maker',
  'Contemporary Toaster',
];

export const marble = [
  'Metropolis Marble',
  'Urbanite Marble',
  'Metro Marble',
  'Cityscape Marble',
  'Skyscraper Marble',
  'Contemporary Marble',
  'Cosmopolitan Marble',
  'Futuristic Marble',
  'Dynamic Marble',
  'Highline Marble',
  'Heritage Marble',
  'Legacy Marble',
  'Tradition Marble',
  'Iconic Marble',
  'Ancestral Marble',
  'Antique Marble',
  'Classic Marble',
  'Historical Marble',
  'Cultural Marble',
  'Authentic Marble',
  'Pure Marble',
  'Simple Marble',
  'Clean Marble',
  'Minimal Marble',
  'Essential Marble',
  'Zen Marble',
  'Sleek Marble',
  'Streamlined Marble',
  'Basic Marble',
  'Understated Marble',
  'Forge Marble',
  'Rustic Marble',
  'Raw Marble',
  'Metal Marble',
  'Steel Marble',
  'Iron Marble',
  'Factory Marble',
  'Industrial Marble',
  'Machined Marble',
  'Workshop Marble',
  'Nexus Marble',
  'Quantum Marble',
  'Cosmos Marble',
  'Horizon Marble',
  'Infinity Marble',
  'Space Age Marble',
  'High-Tech Marble',
  'Digital Marble',
  'Neo Marble',
  'Futuristic Marble',
  'Vintage Marble',
  'Classic Marble',
  'Nostalgia Marble',
  'Antique Marble',
  'Old-fashioned Marble',
  'Retro Marble',
  'Timeless Marble',
  'Traditional Marble',
  'Vintage-inspired Marble',
  'Mid-century Marble',
  'Glamour Marble',
  'Gatsby Marble',
  'Artisan Marble',
  'Deco Marble',
  'Chic Marble',
  'Elegance Marble',
  'Luxury Marble',
  'Art Deco-inspired Marble',
  'Elite Marble',
  'Jazz Age Marble',
  'Pop Marble',
  'Colorful Marble',
  'Funky Marble',
  'Vibrant Marble',
  'Playful Marble',
  'Groovy Marble',
  'Whimsical Marble',
  'Bold Marble',
  'Pop Art-inspired Marble',
  'Graphic Marble',
  'Eames Marble',
  'Atomic Marble',
  'Nelson Marble',
  'Retro Marble',
  'MCM Marble',
  'Danish Marble',
  'Sputnik Marble',
  'Mid-century Marble',
  'Atomic Age Marble',
  'Mad Men Marble',
  'Boho Marble',
  'Natural Marble',
  'Eclectic Marble',
  'Bohemian Marble',
  'Organic Marble',
  'Artisanal Marble',
  'Rustic Marble',
  'Handmade Marble',
  'Tribal Marble',
  'Vintage-inspired Marble',
  'Hygge Marble',
  'Nordic Marble',
  'Minimalist Marble',
  'Scandinavian Marble',
  'Simple Marble',
  'White Marble',
  'Nordic-inspired Marble',
  'Light Marble',
  'Snow Marble',
  'Arctic Marble',
  'Zenith Marble',
  'Elite Marble',
  'Fusion Marble',
  'Contemporary Marble',
  'Modern Marble',
  'Sleek Marble',
  'High-end Marble',
  'High-design Marble',
  'Contemporary-inspired Marble',
  'Designer Marble',
];

export const lightAndDarkStyle = [
  'Soft light',
  'Gentle light',
  'Ethereal light',
  'Radiant light',
  'Sunlight',
  'Golden light',
  'Warm light',
  'Ambient light',
  'Glowing light',
  'Fresh light',
  'Pure light',
  'Crisp light',
  'Clean light',
  'Airy light',
  'Bright light',
  'Illuminated light',
  'Luminous light',
  'Naturalistic light',
  'Daylight',
  'Effulgent light',
  'Darkened',
  'Shadowy',
  'Dim',
  'Gloomy',
  'Mysterious',
  'Noir',
  'Gothic',
  'Macabre',
  'Eerie',
  'Sinister',
  'Moody',
  'Brooding',
  'Ominous',
  'Melancholy',
  'Somber',
  'Blackened',
  'Murky',
  'Twilight',
  'Dusky',
  'Obscure',
];

export const decorateTheItems = [
  'A fruit bowl top',
  'A vase of flowers',
  'A cutting board with fresh herbs and spices',
  'A display of colorful spices and seasonings',
  'A bowl of fresh citrus fruits',
  'A selection of artisanal bread',
  'A cheese board with various cheeses and crackers',
  'A bowl of nuts and dried fruits',
  'A bowl of freshly picked berries',
  'A bottle of wine with wine glasses',
  'A set of tea cups and a tea pot',
  "A decorative plate with hors d'oeuvres or canapes",
  'A collection of vintage jars or bottles',
  'A set of coffee cups and a coffee maker',
  'A display of fresh vegetables and fruits arranged artistically',
  'A collection of exotic fruits or vegetables',
  'A jar of homemade pickles or preserves',
  'A set of colorful mixing bowls and utensils',
  'A dish of olives or pickled vegetables',
  'A basket of fresh bread with butter and jam',
];

export const kindsOfLargeObjects = [
  'The kitchen island',
  'The stove top',
  'The oven',
  'The refrigerator',
  'The sink',
  'The dishwasher',
  'The pantry',
  'The kitchen table',
  'The dining table',
  'The bar counter',
  'The breakfast nook',
  'The coffee table',
  'The side table',
  'The bedside table',
  'The work desk',
  'The reception desk',
  'The cashier counter',
  'The display case',
  'The checkout counter',
  'The retail counter',
];

const products = [
  {
    name: 'Bàn đầu giường bằng đá cẩm thạch veneer',
    description:
      'Veneer bằng đá cẩm thạch mịn mang lại cho chiếc bàn cạnh giường ngủ này một cảm giác quyến rũ. Các ngăn kéo đóng êm giúp sắp xếp các vật dụng trong khi vẫn giữ được bầu không khí yên bình cho phòng ngủ tinh tế của bạn.',
    thumbnailUrl:
      'http://cdn.home-designing.com/wp-content/uploads/2020/03/faux-marble-bedside-table-all-over-pattern-with-tray-tabletop-metal-base-600x600.jpg',
    thumbnails: [
      'http://cdn.home-designing.com/wp-content/uploads/2020/03/faux-marble-bedside-table-all-over-pattern-with-tray-tabletop-metal-base-600x600.jpg',
    ],
    price: 3490000,
    salePrice: 0,
    isSale: false,
    isHot: false,
    isNew: false,
    style: 'Modern',
    isBestSeller: false,
    additionalInformation: {},
    categoryIds: ['c66528a3-78e0-433f-9f79-ce9d5a2d7a7b'],
    roomType: 'Bedroom',
  },
];
